name: Build Debug APK

on:
  # push:
  #   branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.0

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Create Properties File
      run: touch local.properties

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build debug APK
      run: ./gradlew assembleDebug

    - name: Upload APKs
      run: |
        for apk_file in app/build/outputs/apk/debug/*.apk
        do
          artifact_name=$(basename "$apk_file" .apk)
          echo "Uploading $artifact_name..."
          mv "$apk_file" "$artifact_name.apk"
          zip -r "$artifact_name.zip" "$artifact_name.apk"
          rm "$artifact_name.apk"
          echo "::set-output name=artifacts::$artifact_name.zip"
        done
      shell: bash

    - name: Upload Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: ${{ needs.build.outputs.artifacts }}
        path: ./
