name: Build Debug APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.0

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Create Properties File
      run: touch local.properties

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build debug APK
      run: ./gradlew assembleDebug

    - name: Upload APK as Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: arm64-v8a-debug
        path: app/build/outputs/apk/debug/*arm64-v8a-debug.apk
