name: Build Debug APK

on:
  # push:
  #   branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.0

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '16'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build debug APK
      run: bash ./gradlew assembleDebug

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: debug-release.apk
        path: app/build/outputs/apk/debug/app-debug.apk
